#ifndef MAGIC_XE_ERROR_H_
#define MAGIC_XE_ERROR_H_

#include "magic_xe_macros.h"

/**
 * @brief MagicXEError 
 * 
 */
typedef enum MagicXEError {
    // success
    MAGIC_XE_SUCCESS = 0x0000, ///< succeed

    MAGIC_XE_NO_SUCH_FILE,
    MAGIC_XE_INVALID_FILE,
    MAGIC_XE_OUT_OF_MEMORY,
    MAGIC_XE_NOT_IMPLEMENTED,
    MAGIC_XE_CANCEL,
    MAGIC_XE_EOF,
    MAGIC_XE_INVALID_PARAM,
    MAGIC_XE_NOT_FOUND,
    MAGIC_XE_PREPROCESS_NOT_COMPLETE,
    MAGIC_XE_INVALID_MODEL_CONFIG,
    MAGIC_XE_INVALID_MODEL,
    MAGIC_XE_NOT_SUPPORT_DATA_DEVICE,
    MAGIC_XE_INVALID_BLOB,
    MAGIC_XE_FORWARD_ERROR,
    MAGIC_XE_INVALID_MODEL_VERSION,
    MAGIC_XE_NOT_SUPPORT_DEVICE,
    MAGIC_XE_INVALID_CONTEXT,
    MAGIC_XE_INVALID_COMMAND_QUEUE,
    MAGIC_XE_INVALID_RUNTIME,
    MAGIC_XE_DEVICE_NOT_FOUND,
    MAGIC_XE_OPENCL_ERROR,
    MAGIC_XE_OPENGL_ERROR,
    MAGIC_XE_CUDA_ERROR,
    MAGIC_XE_DECODE_ERROR,
    MAGIC_XE_ENCODE_ERROR,

    MAGIC_XE_NOT_INIT_ENV,
    MAGIC_XE_INVALID_LICENSE,

    MAGIC_XE_PLUGIN_NOT_LOAD,
    MAGIC_XE_PLUGIN_FAIL_LOAD,

    MAGIC_XE_INVALID_JSON,
    MAGIC_XE_INVALID_PIPELINE,
    MAGIC_XE_INVALID_DEVICE,

} MagicXEError;

MAGIC_XE_API
const char *MagicXEErrorStringGet(MagicXEError mgxe_err);

/// @}

#endif